/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalysisFailedSwiper: typeof import('./components/AnalysisFailedSwiper.vue')['default']
    CaptureSession: typeof import('./components/CaptureSession.vue')['default']
    ConfirmDialog: typeof import('./components/ConfirmDialog.vue')['default']
    DevToolsDialog: typeof import('./components/DevToolsDialog.vue')['default']
    DevToolsLauncher: typeof import('./components/DevToolsLauncher.vue')['default']
    IconButton: typeof import('./components/IconButton.vue')['default']
    LogoText: typeof import('./components/LogoText.vue')['default']
    NamePhoneDialog: typeof import('./components/NamePhoneDialog.vue')['default']
    PasswordDialog: typeof import('./components/PasswordDialog.vue')['default']
    PrimaryButton: typeof import('./components/PrimaryButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScanSubscription: typeof import('./components/ScanSubscription.vue')['default']
  }
}

// For TSX support
declare global {
  const AnalysisFailedSwiper: typeof import('./components/AnalysisFailedSwiper.vue')['default']
  const CaptureSession: typeof import('./components/CaptureSession.vue')['default']
  const ConfirmDialog: typeof import('./components/ConfirmDialog.vue')['default']
  const DevToolsDialog: typeof import('./components/DevToolsDialog.vue')['default']
  const DevToolsLauncher: typeof import('./components/DevToolsLauncher.vue')['default']
  const IconButton: typeof import('./components/IconButton.vue')['default']
  const LogoText: typeof import('./components/LogoText.vue')['default']
  const NamePhoneDialog: typeof import('./components/NamePhoneDialog.vue')['default']
  const PasswordDialog: typeof import('./components/PasswordDialog.vue')['default']
  const PrimaryButton: typeof import('./components/PrimaryButton.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const ScanSubscription: typeof import('./components/ScanSubscription.vue')['default']
}